package org.ql.shopping.pojo.manifest;

public class ManifestBuy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manifest_buy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manifest_buy.expend_id
     *
     * @mbggenerated
     */
    private Integer expendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manifest_buy.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manifest_buy.user_pay_id
     *
     * @mbggenerated
     */
    private Integer userPayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manifest_buy.id
     *
     * @return the value of manifest_buy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manifest_buy.id
     *
     * @param id the value for manifest_buy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manifest_buy.expend_id
     *
     * @return the value of manifest_buy.expend_id
     *
     * @mbggenerated
     */
    public Integer getExpendId() {
        return expendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manifest_buy.expend_id
     *
     * @param expendId the value for manifest_buy.expend_id
     *
     * @mbggenerated
     */
    public void setExpendId(Integer expendId) {
        this.expendId = expendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manifest_buy.type_id
     *
     * @return the value of manifest_buy.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manifest_buy.type_id
     *
     * @param typeId the value for manifest_buy.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manifest_buy.user_pay_id
     *
     * @return the value of manifest_buy.user_pay_id
     *
     * @mbggenerated
     */
    public Integer getUserPayId() {
        return userPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manifest_buy.user_pay_id
     *
     * @param userPayId the value for manifest_buy.user_pay_id
     *
     * @mbggenerated
     */
    public void setUserPayId(Integer userPayId) {
        this.userPayId = userPayId;
    }
}