package org.ql.shopping.dao.lottery;

import org.ql.shopping.pojo.lottery.LotteryFillUser;

public interface LotteryFillUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lotteryFillUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_user
     *
     * @mbggenerated
     */
    int insert(LotteryFillUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_user
     *
     * @mbggenerated
     */
    int insertSelective(LotteryFillUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_user
     *
     * @mbggenerated
     */
    LotteryFillUser selectByPrimaryKey(Integer lotteryFillUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LotteryFillUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LotteryFillUser record);
}