package org.ql.shopping.dao.lottery;

import org.ql.shopping.pojo.lottery.LotteryFillOpen;

public interface LotteryFillOpenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_open
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lotteryFillOpenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_open
     *
     * @mbggenerated
     */
    int insert(LotteryFillOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_open
     *
     * @mbggenerated
     */
    int insertSelective(LotteryFillOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_open
     *
     * @mbggenerated
     */
    LotteryFillOpen selectByPrimaryKey(Integer lotteryFillOpenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_open
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LotteryFillOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_fill_open
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LotteryFillOpen record);
}