package org.ql.shopping.pojo.lottery;

public class LotteryTypeWithBLOBs extends LotteryType {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lottery_type.lottery_rule
	 *
	 * @mbggenerated
	 */
	private String lotteryRule;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lottery_type.lottery_remark
	 *
	 * @mbggenerated
	 */
	private String lotteryRemark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lottery_type.lottery_rule
	 *
	 * @return the value of lottery_type.lottery_rule
	 *
	 * @mbggenerated
	 */
	public String getLotteryRule() {
		return lotteryRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lottery_type.lottery_rule
	 *
	 * @param lotteryRule
	 *            the value for lottery_type.lottery_rule
	 *
	 * @mbggenerated
	 */
	public void setLotteryRule(String lotteryRule) {
		this.lotteryRule = lotteryRule == null ? null : lotteryRule.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lottery_type.lottery_remark
	 *
	 * @return the value of lottery_type.lottery_remark
	 *
	 * @mbggenerated
	 */
	public String getLotteryRemark() {
		return lotteryRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lottery_type.lottery_remark
	 *
	 * @param lotteryRemark
	 *            the value for lottery_type.lottery_remark
	 *
	 * @mbggenerated
	 */
	public void setLotteryRemark(String lotteryRemark) {
		this.lotteryRemark = lotteryRemark == null ? null : lotteryRemark.trim();
	}
}