package org.ql.shopping.pojo.lottery;

import java.math.BigDecimal;
import java.util.Date;

public class LotteryFillOpen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.lottery_fill_open_id
     *
     * @mbggenerated
     */
    private Integer lotteryFillOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.open_number
     *
     * @mbggenerated
     */
    private String openNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.lottery_fill_creater_date
     *
     * @mbggenerated
     */
    private Date lotteryFillCreaterDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.lottery_fill_end_date
     *
     * @mbggenerated
     */
    private Date lotteryFillEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.create_user_id
     *
     * @mbggenerated
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.fill_l_bi
     *
     * @mbggenerated
     */
    private BigDecimal fillLBi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.award_l_bi
     *
     * @mbggenerated
     */
    private BigDecimal awardLBi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.send_status
     *
     * @mbggenerated
     */
    private String sendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.lottery_fill_unit_price
     *
     * @mbggenerated
     */
    private BigDecimal lotteryFillUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.owner_manifest_id
     *
     * @mbggenerated
     */
    private Integer ownerManifestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_open.lottery_clazz_id
     *
     * @mbggenerated
     */
    private Integer lotteryClazzId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.lottery_fill_open_id
     *
     * @return the value of lottery_fill_open.lottery_fill_open_id
     *
     * @mbggenerated
     */
    public Integer getLotteryFillOpenId() {
        return lotteryFillOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.lottery_fill_open_id
     *
     * @param lotteryFillOpenId the value for lottery_fill_open.lottery_fill_open_id
     *
     * @mbggenerated
     */
    public void setLotteryFillOpenId(Integer lotteryFillOpenId) {
        this.lotteryFillOpenId = lotteryFillOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.open_number
     *
     * @return the value of lottery_fill_open.open_number
     *
     * @mbggenerated
     */
    public String getOpenNumber() {
        return openNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.open_number
     *
     * @param openNumber the value for lottery_fill_open.open_number
     *
     * @mbggenerated
     */
    public void setOpenNumber(String openNumber) {
        this.openNumber = openNumber == null ? null : openNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.lottery_fill_creater_date
     *
     * @return the value of lottery_fill_open.lottery_fill_creater_date
     *
     * @mbggenerated
     */
    public Date getLotteryFillCreaterDate() {
        return lotteryFillCreaterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.lottery_fill_creater_date
     *
     * @param lotteryFillCreaterDate the value for lottery_fill_open.lottery_fill_creater_date
     *
     * @mbggenerated
     */
    public void setLotteryFillCreaterDate(Date lotteryFillCreaterDate) {
        this.lotteryFillCreaterDate = lotteryFillCreaterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.lottery_fill_end_date
     *
     * @return the value of lottery_fill_open.lottery_fill_end_date
     *
     * @mbggenerated
     */
    public Date getLotteryFillEndDate() {
        return lotteryFillEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.lottery_fill_end_date
     *
     * @param lotteryFillEndDate the value for lottery_fill_open.lottery_fill_end_date
     *
     * @mbggenerated
     */
    public void setLotteryFillEndDate(Date lotteryFillEndDate) {
        this.lotteryFillEndDate = lotteryFillEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.create_user_id
     *
     * @return the value of lottery_fill_open.create_user_id
     *
     * @mbggenerated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.create_user_id
     *
     * @param createUserId the value for lottery_fill_open.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.fill_l_bi
     *
     * @return the value of lottery_fill_open.fill_l_bi
     *
     * @mbggenerated
     */
    public BigDecimal getFillLBi() {
        return fillLBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.fill_l_bi
     *
     * @param fillLBi the value for lottery_fill_open.fill_l_bi
     *
     * @mbggenerated
     */
    public void setFillLBi(BigDecimal fillLBi) {
        this.fillLBi = fillLBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.award_l_bi
     *
     * @return the value of lottery_fill_open.award_l_bi
     *
     * @mbggenerated
     */
    public BigDecimal getAwardLBi() {
        return awardLBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.award_l_bi
     *
     * @param awardLBi the value for lottery_fill_open.award_l_bi
     *
     * @mbggenerated
     */
    public void setAwardLBi(BigDecimal awardLBi) {
        this.awardLBi = awardLBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.send_status
     *
     * @return the value of lottery_fill_open.send_status
     *
     * @mbggenerated
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.send_status
     *
     * @param sendStatus the value for lottery_fill_open.send_status
     *
     * @mbggenerated
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.lottery_fill_unit_price
     *
     * @return the value of lottery_fill_open.lottery_fill_unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getLotteryFillUnitPrice() {
        return lotteryFillUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.lottery_fill_unit_price
     *
     * @param lotteryFillUnitPrice the value for lottery_fill_open.lottery_fill_unit_price
     *
     * @mbggenerated
     */
    public void setLotteryFillUnitPrice(BigDecimal lotteryFillUnitPrice) {
        this.lotteryFillUnitPrice = lotteryFillUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.owner_manifest_id
     *
     * @return the value of lottery_fill_open.owner_manifest_id
     *
     * @mbggenerated
     */
    public Integer getOwnerManifestId() {
        return ownerManifestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.owner_manifest_id
     *
     * @param ownerManifestId the value for lottery_fill_open.owner_manifest_id
     *
     * @mbggenerated
     */
    public void setOwnerManifestId(Integer ownerManifestId) {
        this.ownerManifestId = ownerManifestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_open.lottery_clazz_id
     *
     * @return the value of lottery_fill_open.lottery_clazz_id
     *
     * @mbggenerated
     */
    public Integer getLotteryClazzId() {
        return lotteryClazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_open.lottery_clazz_id
     *
     * @param lotteryClazzId the value for lottery_fill_open.lottery_clazz_id
     *
     * @mbggenerated
     */
    public void setLotteryClazzId(Integer lotteryClazzId) {
        this.lotteryClazzId = lotteryClazzId;
    }
}