package org.ql.shopping.pojo.lottery;

import org.ql.shopping.pojo.Model;

public class LotteryFillUser extends Model{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.lottery_fill_user_id
     *
     * @mbggenerated
     */
    private Integer lotteryFillUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.lottery_type_id
     *
     * @mbggenerated
     */
    private Integer lotteryTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.lottery_fill_open_id
     *
     * @mbggenerated
     */
    private Integer lotteryFillOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.lottery_filld_buy_qty
     *
     * @mbggenerated
     */
    private Integer lotteryFilldBuyQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_fill_user.lottery_fill_status
     *
     * @mbggenerated
     */
    private String lotteryFillStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.lottery_fill_user_id
     *
     * @return the value of lottery_fill_user.lottery_fill_user_id
     *
     * @mbggenerated
     */
    public Integer getLotteryFillUserId() {
        return lotteryFillUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.lottery_fill_user_id
     *
     * @param lotteryFillUserId the value for lottery_fill_user.lottery_fill_user_id
     *
     * @mbggenerated
     */
    public void setLotteryFillUserId(Integer lotteryFillUserId) {
        this.lotteryFillUserId = lotteryFillUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.lottery_type_id
     *
     * @return the value of lottery_fill_user.lottery_type_id
     *
     * @mbggenerated
     */
    public Integer getLotteryTypeId() {
        return lotteryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.lottery_type_id
     *
     * @param lotteryTypeId the value for lottery_fill_user.lottery_type_id
     *
     * @mbggenerated
     */
    public void setLotteryTypeId(Integer lotteryTypeId) {
        this.lotteryTypeId = lotteryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.user_id
     *
     * @return the value of lottery_fill_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.user_id
     *
     * @param userId the value for lottery_fill_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.lottery_fill_open_id
     *
     * @return the value of lottery_fill_user.lottery_fill_open_id
     *
     * @mbggenerated
     */
    public Integer getLotteryFillOpenId() {
        return lotteryFillOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.lottery_fill_open_id
     *
     * @param lotteryFillOpenId the value for lottery_fill_user.lottery_fill_open_id
     *
     * @mbggenerated
     */
    public void setLotteryFillOpenId(Integer lotteryFillOpenId) {
        this.lotteryFillOpenId = lotteryFillOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.number
     *
     * @return the value of lottery_fill_user.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.number
     *
     * @param number the value for lottery_fill_user.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.lottery_filld_buy_qty
     *
     * @return the value of lottery_fill_user.lottery_filld_buy_qty
     *
     * @mbggenerated
     */
    public Integer getLotteryFilldBuyQty() {
        return lotteryFilldBuyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.lottery_filld_buy_qty
     *
     * @param lotteryFilldBuyQty the value for lottery_fill_user.lottery_filld_buy_qty
     *
     * @mbggenerated
     */
    public void setLotteryFilldBuyQty(Integer lotteryFilldBuyQty) {
        this.lotteryFilldBuyQty = lotteryFilldBuyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_fill_user.lottery_fill_status
     *
     * @return the value of lottery_fill_user.lottery_fill_status
     *
     * @mbggenerated
     */
    public String getLotteryFillStatus() {
        return lotteryFillStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_fill_user.lottery_fill_status
     *
     * @param lotteryFillStatus the value for lottery_fill_user.lottery_fill_status
     *
     * @mbggenerated
     */
    public void setLotteryFillStatus(String lotteryFillStatus) {
        this.lotteryFillStatus = lotteryFillStatus == null ? null : lotteryFillStatus.trim();
    }
}