package org.ql.shopping.pojo.lottery;

public class StaticLotteryType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_lottery_type.static_lottery_type_id
     *
     * @mbggenerated
     */
    private Integer staticLotteryTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_lottery_type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_lottery_type.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_lottery_type.ramark
     *
     * @mbggenerated
     */
    private String ramark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_lottery_type.static_lottery_type_id
     *
     * @return the value of static_lottery_type.static_lottery_type_id
     *
     * @mbggenerated
     */
    public Integer getStaticLotteryTypeId() {
        return staticLotteryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_lottery_type.static_lottery_type_id
     *
     * @param staticLotteryTypeId the value for static_lottery_type.static_lottery_type_id
     *
     * @mbggenerated
     */
    public void setStaticLotteryTypeId(Integer staticLotteryTypeId) {
        this.staticLotteryTypeId = staticLotteryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_lottery_type.name
     *
     * @return the value of static_lottery_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_lottery_type.name
     *
     * @param name the value for static_lottery_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_lottery_type.type
     *
     * @return the value of static_lottery_type.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_lottery_type.type
     *
     * @param type the value for static_lottery_type.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_lottery_type.ramark
     *
     * @return the value of static_lottery_type.ramark
     *
     * @mbggenerated
     */
    public String getRamark() {
        return ramark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_lottery_type.ramark
     *
     * @param ramark the value for static_lottery_type.ramark
     *
     * @mbggenerated
     */
    public void setRamark(String ramark) {
        this.ramark = ramark == null ? null : ramark.trim();
    }
}